### ISSUE TITLE
Failing to parse old text format for (8-K Filings)

### ISSUE THREAD

**Issue by ch99q** [dgunning/edgartools#174]
I've been testing the tool on old company 8-K filings from companies such as ALTABA INC. (former Yahoo! Inc.)

It fails for some reason, even when companies like Nvidia's oldest 8-K filings uses same format, seems to parse just fine.

```
>>> c = Company(1011006)
>>> c
╭──────────────────────────────────────────────────── 🏢ALTABA INC. ─────────────────────────────────────────────────────╮
│                                                                                                                        │
│                                                                                                                        │
│ ╭──────────────────────────────────────────────────── 📋 Entity ─────────────────────────────────────────────────────╮ │
│ │                                                                                                                    │ │
│ │   CIK   1011006   Type   Operating   ○                                                                             │ │
│ │                                                                                                                    │ │
│ │                                                                                                                    │ │
│ │   Category            Industry   Fiscal Year End                                                                   │ │
│ │  ────────────────────────────────────────────────                                                                  │ │
│ │   Large Accelerated   -          Dec 31                                                                            │ │
│ │                                                                                                                    │ │
│ ╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯ │
│ ╭────────────────────────────────────────────── 📈 Trading Information ──────────────────────────────────────────────╮ │
│ │ No trading information available                                                                                   │ │
│ ╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯ │
│ ╭───── 🏢 Business Address ─────╮             ╭───── 📫 Mailing Address ─────╮ ╭─── 📞 Contact Information ────╮       │
│ │ ALTABA INC.                   │             │ 140 E. 45TH STREET           │ │                               │       │
│ │ 140 E. 45TH STREET 15TH FLOOR │             │ 15TH FLOOR                   │ │   Phone   (646) 679-2000      │       │
│ │ NEW YORK, NY 10017            │             │ NEW YORK, NY 10017           │ │                               │       │
│ ╰───────────────────────────────╯             ╰──────────────────────────────╯ ╰───────────────────────────────╯       │
│ ╭───────────────────────────────────────────────── 📜 Former Names ──────────────────────────────────────────────────╮ │
│ │                                                                                                                    │ │
│ │   YAHOO INC   August 1996 to June 2017                                                                             │ │
│ │                                                                                                                    │ │
│ ╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯ │
╰─────────────────────────────────────────────────── SEC Entity Data ────────────────────────────────────────────────────╯

>>> c.get_filings(form="8-K").tail(35)
╭────────────────────────────────────────── Filings for ALTABA INC. [1011006] ───────────────────────────────────────────╮
│                                                                                                                        │
│    #   Form       Description                                          Filing Date   Accession Number                  │
│  ─────────────────────────────────────────────────────────────────────────────────────────────────────────             │
│    0   8-K        Current report                                       2002-01-18    0000912057-02-001744              │
│    1   8-K        Current report                                       2002-01-11    0000912057-02-001099              │
│    2   8-K        Current report                                       2001-12-27    0000912057-01-544727              │
│    3   8-K        Current report                                       2001-12-13    0000912057-01-543046              │
│    4   8-K        Current report                                       2001-11-16    0000912057-01-540276              │
│    5   8-K        Current report                                       2001-10-11    0001104659-01-502276              │
│    6   8-K        Current report                                       2001-07-12    0000912057-01-523593              │
│    7   8-K        Current report                                       2001-04-17    0000912057-01-509174              │
│    8   8-K        Current report                                       2001-04-12    0000912057-01-508433              │
│    9   8-K        Current report                                       2001-03-19    0000912057-01-007754              │
│   10   8-K        Current report                                       2001-03-08    0000912057-01-007396              │
│   11   8-K        Current report                                       2001-01-10    0000912057-01-000998              │
│   12   8-K        Current report                                       2000-10-11    0000912057-00-044467              │
│   13   8-K        Current report                                       2000-09-01    0000912057-00-039992              │
│   14   8-K        Current report                                       2000-08-11    0000912057-00-036624              │
│   15   8-K        Current report                                       2000-07-12    0000912057-00-031620              │
│   16   8-K        Current report                                       2000-06-29    0000912057-00-030453              │
│   17   8-K        Current report                                       2000-04-06    0000912057-00-016486              │
│   18   8-K        Current report                                       2000-01-12    0000912057-00-000968              │
│   19   8-K        Current report                                       1999-10-07    0001047469-99-038084              │
│   20   8-K        Current report                                       1999-07-20    0001047469-99-028059              │
│   21   8-K        Current report                                       1999-07-08    0001047469-99-026618              │
│   22   8-K        Current report                                       1999-06-02    0001047469-99-022911              │
│   23   8-K        Current report                                       1999-04-08    0001047469-99-013985              │
│   24   8-K        Current report                                       1999-04-05    0001047469-99-013634              │
│   25   8-K        Current report                                       1999-01-29    0001047469-99-002569              │
│   26   8-K        Current report                                       1999-01-13    0001047469-99-001083              │
│   27   8-K        Current report                                       1998-10-23    0001047469-98-038051              │
│   28   8-K        Current report                                       1998-07-09    0001047469-98-026797              │
│   29   8-K        Current report                                       1998-06-12    0001047469-98-024003              │
│   30   8-K        Current report                                       1998-06-08    0001047469-98-023329              │
│   31   8-K        Current report                                       1998-01-15    0001047469-98-001221              │
│   32   8-K        Current report                                       1998-01-05    0001047469-98-000122              │
│   33   8-K        Current report                                       1997-10-14    0001012870-97-001956              │
│   34   8-K        Current report                                       1997-08-04    0000912057-97-025972              │
│                                                                                                                        │
╰────────────────────────────────── Company filings between 1997-08-04 and 2002-01-18 ───────────────────────────────────╯

>>> c.get_filings(form="8-K").tail(35).get(0).obj()
/opt/homebrew/anaconda3/lib/python3.12/site-packages/edgar/files/htmltools.py:271: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  chunk_df.Item = chunk_df.Item.ffill().infer_objects(copy=False)
╭─────────────────────────────────────────── ALTABA INC. 8-K January 16, 2002 ───────────────────────────────────────────╮
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

>>> c.get_filings(form="8-K").tail(35).get(32).obj()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/anaconda3/lib/python3.12/site-packages/edgar/company_reports.py", line 651, in __repr__
    return repr_rich(self.__rich__())
                     ^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/lib/python3.12/site-packages/edgar/company_reports.py", line 642, in __rich__
    for item in self.items:
                ^^^^^^^^^^
  File "/opt/homebrew/anaconda3/lib/python3.12/site-packages/edgar/company_reports.py", line 621, in items
    return self.chunked_document.list_items()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/lib/python3.12/site-packages/edgar/company_reports.py", line 612, in chunked_document
    return ChunkedDocument(self._filing.html(),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/lib/python3.12/site-packages/edgar/files/htmltools.py", line 308, in __init__
    self.chunks = chunk(html)
                  ^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/lib/python3.12/site-packages/edgar/files/htmltools.py", line 96, in chunk
    document = HtmlDocument.from_html(html)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/lib/python3.12/site-packages/edgar/files/html_documents.py", line 438, in from_html
    root: Tag = cls.get_root(html)
                ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/lib/python3.12/site-packages/edgar/files/html_documents.py", line 426, in get_root
    if "<TEXT>" in html[:500]:
                   ~~~~^^^^^^
TypeError: 'NoneType' object is not subscriptable
>>> c.get_filings(form="8-K").tail(35).get(32)
╭───────────────────────────────────────────── ALTABA INC. [1011006] 8-K 📄 ─────────────────────────────────────────────╮
│ ╭──────────────────────┬────────────╮                                                                                  │
│ │ 0001047469-98-000122 │ 1998-01-05 │                                                                                  │
│ ╰──────────────────────┴────────────╯                                                                                  │
│ ╭────────────────────────────────────────────────────────────────────────────────────────────╮                         │
│ │ Links: 🏠 Homepage 📄 Primary Document 📜 Full Submission Text                             │                         │
│ ├────────────────────────────────────────────────────────────────────────────────────────────┤                         │
│ │ 🏠 https://sec.gov/Archives/edgar/data/1011006/0001047469-98-000122-index.html             │                         │
│ │ 📄 https://sec.gov/Archives/edgar/data/1011006/                                            │                         │
│ │ 📜 https://sec.gov/Archives/edgar/data/1011006/000104746998000122/0001047469-98-000122.txt │                         │
│ ╰────────────────────────────────────────────────────────────────────────────────────────────╯                         │
╰─────────────────────────────────────────────── Form 8-K: Current report ───────────────────────────────────────────────╯

>>> c.get_filings(form="8-K").tail(35).get(0)
╭───────────────────────────────────────────── ALTABA INC. [1011006] 8-K 📄 ─────────────────────────────────────────────╮
│ ╭──────────────────────┬────────────╮                                                                                  │
│ │ 0000912057-02-001744 │ 2002-01-18 │                                                                                  │
│ ╰──────────────────────┴────────────╯                                                                                  │
│ ╭────────────────────────────────────────────────────────────────────────────────────────────╮                         │
│ │ Links: 🏠 Homepage 📄 Primary Document 📜 Full Submission Text                             │                         │
│ ├────────────────────────────────────────────────────────────────────────────────────────────┤                         │
│ │ 🏠 https://sec.gov/Archives/edgar/data/1011006/0000912057-02-001744-index.html             │                         │
│ │ 📄 https://sec.gov/Archives/edgar/data/1011006/000091205702001744/a2068061z8-k.htm         │                         │
│ │ 📜 https://sec.gov/Archives/edgar/data/1011006/000091205702001744/0000912057-02-001744.txt │                         │
│ ╰────────────────────────────────────────────────────────────────────────────────────────────╯                         │
╰─────────────────────────────────────────────── Form 8-K: Current report ───────────────────────────────────────────────╯
```

**Comment by dgunning** [comment]
Thanks for reporting this. I had made some changes recently to html parsing and especially how 10Ks and 10Qs are displayed. I had not yet come to 8-k and I do need to do some improvements. 

I found the code that caused that specific bug, but I now need to figure out how to display the 8-K in terms of what is important to show. Currently it displays items of the 8-K which were parsed from the HTML. The HTML for all our filings is empty. However, the actual filing was placed in the submission text. I think I can pull it from the submission text and then display it. Basically, what I'm saying is: I found the bug, I fixed the bug, but I do need to think about what's the best way to display what an AK contains.

**Comment by dgunning** [comment]
Fixed
