### ISSUE TITLE
AttributeError: module 'tenacity' has no attribute 'wait_exponential_jitter'

### ISSUE THREAD

**Issue by Almie** [dgunning/edgartools#94]
Hi, I get this error when importing the library:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...\venv\lib\site-packages\edgar\__init__.py", line 9, in <module>
    from edgar.entities import (Company,
  File "...\venv\lib\site-packages\edgar\entities.py", line 24, in <module>
    from edgar._filings import Filing, Filings, FilingsState
  File "...\venv\lib\site-packages\edgar\_filings.py", line 38, in <module>
    from edgar.attachments import FilingHomepage, Attachment, Attachments, AttachmentServer
  File "...\venv\lib\site-packages\edgar\attachments.py", line 27, in <module>
    from edgar.httprequests import get_with_retry, download_file, download_file_async
  File "...\venv\lib\site-packages\edgar\httprequests.py", line 158, in <module>
    @retry(on=httpx.RequestError, attempts=attempts, timeout=retry_timeout, wait_initial=wait_initial)
  File "...\venv\lib\site-packages\stamina\_core.py", line 581, in retry
    retry_ctx = _RetryContextIterator.from_params(
  File "...\lib\site-packages\stamina\_core.py", line 393, in from_params
    "wait": _t.wait_exponential_jitter(
AttributeError: module 'tenacity' has no attribute 'wait_exponential_jitter'

Steps to reproduce:
1. `pip install edgartools`
2. `from edgar import *`

Python version: 3.9.13
OS: Windows 10

EDIT: Managed to solve issue by running `pip install tenacity==8.3.0`. It seems that your dependency is set to `tenacity<8.4.0` which for some reason by default installed 7.0.0 version which is missing wait_exponential_jitter.

**Comment by dgunning** [comment]
Thanks for investigating. Will check the version compatibility of the libraries and issue a fix

**Comment by dgunning** [comment]
Tenacity is pinned in release 2.29.0
